version: '3.9'

services:
  sample-api-app:
    container_name: backend-api
    build: ./
    command: npm start
    # environment:
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_HOST: ${MYSQL_HOST}
    working_dir: /usr/src/node-sample-project
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/node-sample-project
    depends_on:
      - db

  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
    ports: 
      - '3306:3306'

